site_name: 'mkdocs template'
site_description: 'A site for mkdocs template'
site_author: 'nueks'
site_url: 'https://nueks.github.io/mkdocs-template'
repo_name: 'Github'
repo_url: 'https://github.com/nueks/mkdocs-template'
copyright: Copyright &copy; 2021 - 2022 <a href="https://github.com/nueks" target="_blank">nueks</a>
docs_dir: 'docs/'

theme:
  name: 'material'
  static_templates:
  - 404.html
  include_search_page: false
  search_index_only: true
  features:
  # - header.autohide
  - navigation.tabs
  - navigation.top
  - search.highlight
  - toc.integrate
  - content.code.annotate
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - scheme: slate
    primary: red
    accent: red
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/favicon.png
  # icon:
  #   logo: logo

markdown_extensions:
- abbr
- meta
- tables
- footnotes
- attr_list
- md_in_html
- def_list
- admonition
- pymdownx.snippets
- pymdownx.details
- pymdownx.superfences
- pymdownx.betterem
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.keys
- pymdownx.smartsymbols
- pymdownx.inlinehilite
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- toc:
    permalink: true
    toc_depth: 2

extra_javascript:
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
- stylesheets/extra.css

nav:
- Home: README.md
- Links:
    - References: reference.md
    - Test: test.md
