site_name: 'mkdocs template'
site_description: 'A site for mkdocs template'
site_author: 'nueks'
docs_dir: 'docs/'
repo_name: 'nueks/mkdocs-template'
repo_url: 'https://github.com/nueks/mkdocs-template'
nav:
- Home: index.md
- Reference: reference.md
theme:
  name: 'material'
  palette:
    primary: green
  features:
  - header.autohide
  - navigation.tabs
  - toc.integrate

markdown_extensions:
- admonition
- footnotes
